# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cq8c1fnyj-capi-aws
  namespace: cq8c1fnyj
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cq8c1fnyj-capi-aws
subjects:
- kind: ServiceAccount
  name: cq8c1fnyj-capi-aws
